FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
WORKDIR /app

# Сначала копируем только pom.xml для кэширования зависимостей
COPY pom.xml .
RUN mvn dependency:go-offline

# Затем копируем исходный код и собираем проект
COPY src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:21-jre-alpine
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]
